language: cpp
compiler: g++
before_install: 
    - sudo apt-get update -qq
    - sudo apt-get purge libboost*1.46*
    - sudo apt-get install libboost1.55-all-dev
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
